name: Notify Discord on Push

on:
  push:
    branches:
      - dev
      - main

jobs:
  webhook-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set environment variables
      id: vars
      run: |
        echo "MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub",
        "content": "",
        "embeds": [
          {
            "type": "rich",
            "title": "Обновление → ${{ github.repository }} (Посмотреть)",
            "description": "### Репозиторий: ${{ github.repository }}\n### Ветка: ${{ env.BRANCH }}\n💬 ${{ env.MESSAGE }}",
            "color": 2123412,
            "thumbnail": {
              "url": "https://avatars.githubusercontent.com/u/187317391?s=400&u=50c91de3e0bdbb0249ec6fbb82a0cd83b6791ff9&v=4"
            },
            "author": {
              "name": "${{ github.actor }}",
              "url": "https://github.com/${{ github.actor }}",
              "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
            },
            "url": "https://github.com/${{ github.repository }}/commit/${{ env.COMMIT_HASH }}"
          }
        ]
        }' ${{ secrets.DISCORD_WEBHOOK_URL }})
        echo "Webhook server response: $RESPONSE"
